#https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html 에서 속성 확인 가능

server:
  address: localhost
  port: 8081
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 1m

management:
  endpoints:
    web:
      exposure:
        include: '*'